name: my_portfolio
description: "Mohaned Portfolio"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.6
  # device_preview: ^1.2.0
  flutter:
    sdk: flutter
  flutter_map: ^7.0.2
  flutter_map_cancellable_tile_provider: ^3.0.0
  flutter_svg: ^2.0.10+1
  # gap: ^3.0.1
  google_fonts: ^6.2.1
  hexcolor: ^3.0.1
  latlong2: ^0.9.1
  smooth_page_indicator: ^1.2.0+3
  # url_launcher: ^6.3.0

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  # flutter_launcher_icons: ^0.13.1


flutter:

  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

  fonts:
    - family: MavenPro
      fonts:
        - asset: assets/fonts/MavenPro-Regular.ttf
          weight: 400
        - asset: assets/fonts/MavenPro-Bold.ttf
          weight: 700
